### ISSUE TITLE
Module `modul-test/renderIf` does not exist in the Haste module map

### ISSUE THREAD

**Issue by akash0208** [musicpro/react-native-scrollview-indicator#1]
I am trying to implement this library in my code and I found this error. When I checked its file 'scrollViewWithIndicator.js', it imported this file but didn't exist anywhere.

**Comment by musicpro** [comment]
Oh thanks for pointing this out! Just checked the code and noticed that this actually had to be cleaned and put in the description as well. So actually it is a pretty easy fix:

Just add a new file to your project and call it renderIf.js.
Inside this file use the following code:

```javascript
'use strict'; 
const isFunction = input => typeof input === 'function';
export default predicate => elemOrThunk =>
    predicate ? (isFunction(elemOrThunk) ? elemOrThunk() : elemOrThunk) : null;
```

Now just import that file in ScrollVIewWithIndicator.js. Instead of: (line 12)
```javascript
import renderIf from 'modul-test/renderIf';
```

put: 

```javascript
import renderIf from 'Path/To/renderIf';
```

This is fix needs to be done in the downloaded package inside the node_modules dir.
If you can wait or don't want to do this now, I will upload a fix for this soon!!

Hope I could help you, if not just write again and we try an other way :)

**Comment by akash0208** [comment]
I followed these steps but now found this error.
![screenshot_1545891452](https://user-images.githubusercontent.com/26005695/50468338-4f023080-09cd-11e9-8df6-f7b2accb8885.png)

**Comment by musicpro** [comment]
Sorry for the late response! 
Could you provide the code where this is happening? Seems like this is not a problem of my module.
But lets figure this out ;)

BTW I updated the module to work with the renderIf. So no need to fix this on your end anymore.

**Comment by nwaughachukwuma** [comment]
@musicpro I experienced this problem too. Is this fix in a release? As in will I get it when I update the library? Also, what am I to update to? Finally, is this like a direct replacement for scrollview? Your example doesn't show much. How do I use it with a flatlist?

Thanks

**Comment by musicpro** [comment]
the renderIf not found issue? Yes that should be fixed after installing the new update/release. 
To update simply run npm install or yarn. This should update the package.
Sorry if it is not that clear in my README. But it is a replacement for ScrollView.
The point is that there is a huge difference between ScrollView and FlatList. So you can't use it with a FlatList. 
As written in the README you can use it as a usual ScrollView component it simply has some more props :)

**Comment by nwaughachukwuma** [comment]
Alright @musicpro  thanks for the quick response.

**Comment by musicpro** [comment]
No problem :)
If you need more help, feel free to ask. But maybe not in this post ;)

**Comment by musicpro** [comment]
@akash0208 is your problem solved or do you need more help? Would like to close this issue if everything is working with my package. :)

**Comment by akash0208** [comment]
Thank you @musicpro for your quick response, this resolves my issue. 
Thanks for your support🙂
